# Generated by Django 4.1.3 on 2022-11-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('fecha_nacimiento', models.DateField()),
                ('parentesco', models.CharField(max_length=40)),
                ('ocupacion', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
            ],
        ),
    ]
